---
- name: Create EPICS home directory
  file: path=/opt/epics state=directory mode=0755

- name: Install EPICS compiled tarball (skip if /opt/epics/base exists)
  unarchive: src=epics.tar.gz dest=/opt/epics creates=/opt/epics/base

- name: Setup /etc/bash.bashrc with EPICS environment variables
  blockinfile: 
    dest: /etc/bash.bashrc 
    marker: "# {mark} ANSIBLE epics MANAGED BLOCK"
    insertafter: EOF
    state: present
    block: |
      export EPICS_BASE="/opt/epics/base"
      export EPICS_HOST_ARCH=`${EPICS_BASE}/startup/EpicsHostArch`
      export PATH="${PATH}:${EPICS_BASE}/bin/${EPICS_HOST_ARCH}"
      export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${EPICS_BASE}/lib/${EPICS_HOST_ARCH}"

