---
- name: Create EPICS home directory
  file: path=/opt/epics state=directory mode=0755

- name: Install EPICS compiled tarball (skip if /opt/epics/base exists)
  unarchive: src=epics.tar.gz dest=/opt/epics creates=/opt/epics/base

- name: Setup /etc/bash.bashrc with EPICS environment variables
  template: src=epics.j2 dest=/root/.bash.conf.d/epics.sh
